title: 米国株・中国株・仮想通貨で資産運用
email: 
description: 40代サラリーマンの資産運用ブログです。米国株、中国株、FX、仮想通貨などに投資しています。
baseurl: ""
url: "http://finvx.com"
twitter_username: finvxcom
github_username:  finvx

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
  shortname: finvx

google_analytics: UA-75214419-1
