title: Financial Virtual Experiment
email: 
description: 資産運用ブログ
baseurl: ""
permalink: /:title/
url: "http://finvx.com"
twitter_username: finvx
github_username:  finvx

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
  shortname: finvx

google_analytics: UA-75214419-1
