title: Financial Virtual Experiment
email: admin@finvx.com
description: 
baseurl: ""
url: "http://finvx.com"
twitter_username: finvx
github_username:  finvx

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
